mp:
  messaging:
    connector:
      smallrye-kafka:
        bootstrap:
          servers: bs-kafka:9092
    outgoing:
      to-kafka:
        connector: smallrye-kafka
        topic: testing
        key:
          serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value:
          serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        schema:
          registry:
            url: http://bs-schema-registry:8085
    incoming:
      from-kafka:
        connector: smallrye-kafka
        topic: testing
        value:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
        schema:
          registry:
            url: http://bs-schema-registry:8085
        specific:
          avro:
            reader: true
