mp:
  messaging:
    connector:
      smallrye-kafka:
        bootstrap:
          servers: bs-kafka:9092
    outgoing:
      to-kafka-avro:
        connector: smallrye-kafka
        topic: testing-avro
        key:
          serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value:
          serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        schema:
          registry:
            url: http://bs-schema-registry:8085
      to-kafka-string:
        connector: smallrye-kafka
        topic: testing-string
        key:
          serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
    incoming:
      from-kafka-avro:
        connector: smallrye-kafka
        topic: testing-avro
        value:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
        schema:
          registry:
            url: http://bs-schema-registry:8085
        specific:
          avro:
            reader: true
      from-kafka-string:
        connector: smallrye-kafka
        topic: testing-string
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
