apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    uid: fixeduid
    url: http://prometheus:9090
  - name: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686

