version: "3.8"

# run from project directory
# docker-compose -f ./etc/docker-compose/docker-compose.local.observability.yml up --build --force-recreate
services:
    prometheus:
        container_name: prometheus
        volumes:
            - '../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
        image: dockerhub-dockerio.icellmobilsoft.hu/prom/prometheus:v2.40.2
        ports:
            - '9090:9090'
    grafana:
        container_name: grafana
        volumes:
            - '../config/grafana/provisioning/:/etc/grafana/provisioning/'
        image: dockerhub-dockerio.icellmobilsoft.hu/grafana/grafana:9.2.6
        ports:
            - '3000:3000'
networks:
    default:
        external:
            # if it could not be found on compose up, then execute: docker network create bs-local-network
            name: bs-local-network
