version: "3.8"

# futtatas
# docker compose -f <PROJECT_PATH>/backend-sampler/etc/docker-compose/docker-compose.local.wildfly.yml up --build --force-recreate
#
# belemaszas
# docker exec -it bs-sample-service /bin/bash
#
# uresbe inditas
# docker run --rm -it docker-compose_sample-service /bin/bash
services:
  sample-service:
    container_name: bs-sample-service
    image: icellmobilsoft/wildfly-mp-full:2.0.0-SNAPSHOT
    volumes:
      - './wildfly/sample.properties:/home/icellmobilsoft/config/wildfly.properties'
    ports:
      - '8081:8080'
      - '9991:9990'
      - '8788:8787'
      - '8199:8199' #GRPC
    environment:
      OPENTRACING_JAEGER_AGENT_HOST: jaeger
      JAEGER_SERVICE_NAME: bs-sample-service
#      MP_CONFIG_PROFILE: redispubsub
      MP_CONFIG_PROFILE: kafka
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
networks: 
  default: 
    external: 
      name: bs-local-network
